[package]
name = "slq"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []

[dependencies]
anyhow = { version = "1.0.45", default-features = false }
borsh = "0.9.0"
borsh-derive = "0.9.0"
solana-program = "1.8.2"
